name: Get Latest Release Number
description: Get the latest release number from the repository

runs:
  using: "composite"
  steps:
    - name: Get Latest Release Number
      id: get-latest-release-number
      run: |
        #!/bin/bash
        set -e

        # Get the latest release branch based on version
        latest_tag=$(git tag | grep '^release/' | sort -V | tail -n 1)

        # Extract just the version part
        version_number=$(echo "$latest_tag" | sed 's/^release\///')

        # Set the default branch if no release branch exists
        # if [ -z "$version_number" ]; then
        #   echo "No release branch found."
        #   exit 1
        # fi

        echo "Latest release branch: ${version}"
        echo "LATEST_BRANCH=${version_number}" >> $GITHUB_ENV
      shell: bash
