name: Get Latest Release Number
description: Get the latest release number from the repository

runs:
  using: "composite"
  steps:
    - name: Get Latest Release Number
      id: get-latest-release-number
      run: |
        #!/bin/bash
        set -e

        # Get the latest release tag based on version
        latest_tag=$(git tag | grep '^release/' | sort -V | tail -n 1)

        # Check if a release tag was found
        if [ -z "$latest_tag" ]; then
          echo "No release tag found."
          echo "LATEST_BRANCH=" >> $GITHUB_ENV
          exit 1
        fi

        # Extract just the version part
        version_number=$(echo "$latest_tag" | sed 's/^release\///')

        # Print and set the environment variable
        echo "Latest release tag: $latest_tag"
        echo "LATEST_BRANCH=${version_number}" >> $GITHUB_ENV
      shell: bash
