name: App hotfix Process

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: "Tag of the latest stable version"
        required: true
      hotfixBranch:
        description: "Name of the hotfix branch"
        required: true

jobs:
  create-hotfix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create hotfix branch from tag
        run: |
          #!/bin/bash
          set -e

          TAG_NAME="${{ github.event.inputs.tagName }}"
          HOTFIX_BRANCH="${{ github.event.inputs.hotfixBranch }}"

          # Check if the tag exists
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME exists. Creating hotfix branch $HOTFIX_BRANCH from $TAG_NAME."
          else
            echo "Tag $TAG_NAME does not exist. Exiting."
            exit 1
          fi

          # Create and checkout the hotfix branch from the tag
          git checkout -b $HOTFIX_BRANCH $TAG_NAME

          # Push the hotfix branch to the remote repository
          git push origin $HOTFIX_BRANCH
        shell: bash
        env:
          SECRET: ${{ secrets.GH_SECRET }}
