name: App hotfix Process

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: "Tag of the latest stable version"
        required: true
      hotfixBranch:
        description: "Name of the hotfix branch"
        required: true

permissions:
  contents: write # Permite escribir en los contenidos del repositorio

jobs:
  create-hotfix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up environment variables
        id: setup-env
        run: |
          echo "TAG_NAME=${{ github.event.inputs.tagName }}" >> $GITHUB_ENV
          echo "HOTFIX_BRANCH=${{ github.event.inputs.hotfixBranch }}" >> $GITHUB_ENV

      - name: Validate tag and create hotfix branch
        run: |
          #!/bin/bash
          set -e

          # Check if the tag exists
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME exists. Creating hotfix branch $HOTFIX_BRANCH from $TAG_NAME."
          else
            echo "Tag $TAG_NAME does not exist. Exiting."
            exit 1
          fi
        env:
          SECRET: ${{ secrets.GH_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GH_SECRET }}

      - name: Create hotfix branch
        run: |
          #!/bin/bash
          set -e

          # Create a new branch from the tag
          git checkout -b $HOTFIX_BRANCH $TAG_NAME
          git push origin $HOTFIX_BRANCH
        env:
          SECRET: ${{ secrets.GH_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GH_SECRET }}

  merge-hotfix:
    needs: create-hotfix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        id: setup-env
        run: |
          echo "TAG_NAME=${{ github.event.inputs.tagName }}" >> $GITHUB_ENV
          echo "HOTFIX_BRANCH=${{ github.event.inputs.hotfixBranch }}" >> $GITHUB_ENV

      # we need to create new tag for the hotfix branch

      - name: Delete hotfix branch
        run: |
          #!/bin/bash
          set -e

          # Delete the hotfix branch locally and remotely
          git branch -d "$HOTFIX_BRANCH"
          git push origin --delete "$HOTFIX_BRANCH"
        shell: bash
        env:
          SECRET: ${{ secrets.GH_SECRET }}
