name: generate-app-release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release version type"
        required: true
        default: "minor"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  generate-app-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment variables
        id: setup-env
        run: |
          echo "RELEASE_TYPE=${{ github.event.inputs.releaseType }}" >> $GITHUB_ENV

      - name: Get latest release branch
        id: get-latest-release
        run: |
          # Get the latest release branch based on version
          # v. prefix
          # latest_tag=$(git tag --list 'v*' | sort -V | tail -n 1)
          latest_tag=$(git tag --list | grep release/ | tail -n 1)
          # Extract just the version part
          version=${latest_tag#release/}

          echo "Latest release branch: ${latest_tag} ${version}"

          # Set the default branch if no release branch exists
          if [ -z "$version" ]; then
            echo "No release branch found."
            exit 1
          fi

          echo "Latest release branch: ${version}"
          echo "LATEST_BRANCH=${version}" >> $GITHUB_ENV

      - name: validate release version
        run: |
          chmod +x validate-release-version.sh
          ./validate-release-version.sh

      - name: Increment version based on release type
        id: increment-version
        uses: ./.github/actions/increment-app-version
        with:
          branch_name: $LATEST_BRANCH
          release_type: $RELEASE_TYPE

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if branch exists
        id: check-branch
        run: |
          if git show-ref --quiet refs/heads/"$NEW_BRANCH_NAME" || git show-ref --quiet refs/remotes/origin/"$NEW_BRANCH_NAME"; then
            echo "Branch '${NEW_BRANCH_NAME}' already exists."
            exit 1
          else
            echo "Branch '${NEW_BRANCH_NAME}' does not exist."
          fi

      - name: Create release branch
        run: |
          git checkout -b $NEW_BRANCH_NAME
          git push origin $NEW_BRANCH_NAME
        env:
          SECRET: ${{ secrets.GH_SECRET }}
