name: generate-app-release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release version type"
        required: true
        default: "minor"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  generate-app-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment variables
        id: setup-env
        run: |
          echo "RELEASE_TYPE=${{ github.event.inputs.releaseType }}" >> $GITHUB_ENV

      - name: Get Latest Release Number
        id: get-latest-release-number
        uses: ./.github/actions/get-latest-release-number
        env:
          SECRET: ${{ secrets.GH_SECRET }}

      - name: validate release version
        run: |
          chmod +x validate-release-version.sh
          ./validate-release-version.sh

      - name: Increment version based on release type
        run: |
          echo "Incrementing version based on release type ${{ github.event.inputs.releaseType }}"

      - name: Increment version based on release type
        id: increment-version
        uses: ./.github/actions/increment-app-version
        with:
          LATEST_BUILD_NUMBER: ${{ env.LATEST_BRANCH }}
          TYPE: ${{ github.event.inputs.releaseType }}

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if branch exists
        id: check-branch
        run: |
          if git show-ref --quiet refs/heads/"$NEW_BRANCH_NAME" || git show-ref --quiet refs/remotes/origin/"$NEW_BRANCH_NAME"; then
            echo "Branch '${NEW_BRANCH_NAME}' already exists."
            exit 1
          else
            echo "Branch '${NEW_BRANCH_NAME}' does not exist."
          fi

      - name: Create release branch
        run: |
          git checkout -b $NEW_BRANCH_NAME
          git push origin $NEW_BRANCH_NAME
        env:
          SECRET: ${{ secrets.GH_SECRET }}
