name: generate-app-release

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Nombre de la nueva rama"
        required: true
        default: "1.0.0"

jobs:
  generate-app-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: validate release version
        run: |
          chmod +x validate-release-version.sh        
          ./validate-release-version.sh
        env:
          BRANCH_NAME: ${{ github.event.inputs.branch_name }}

      - name: Setup Git
        run: |
          git config --global user.name "test"
          git config --global user.email "test@test.com"

      - name: Se  t up environment variables
        id: setup-env
        run: |
          echo "BRANCH_NAME=release/${{ github.event.inputs.branch_name }}" >> $GITHUB_ENV

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if branch exists
        id: check-branch
        run: |
          if git show-ref --quiet refs/heads/"$BRANCH_NAME" || git show-ref --quiet refs/remotes/origin/"$BRANCH_NAME"; then
            echo "Branch '${BRANCH_NAME}' already exists."
            echo "exists=true" >> $GITHUB_ENV
            exit 1
          else
            echo "Branch '${BRANCH_NAME}' does not exist."
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Create release branch
        run: |
          git fetch

          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
        env:
          SECRET: ${{ secrets.GH_SECRET }}
