name: generate-app-release

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Nombre de la nueva rama"
        required: true
        default: "1.0.0"

jobs:
  generate-app-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "test"
          git config --global user.email "test@test.com"

      - name: validate release version
        run: |
          chmod +x validate-release-version.sh        
          ./validate-release-version.sh
        env:
          BRANCH_NAME: ${{ github.event.inputs.branch_name }}

          # check if the branch already exists
      - name: Create release branch
        run: |
          git fetch

          git checkout -b release/${{ github.event.inputs.branch_name }}
          git push origin release/${{ github.event.inputs.branch_name }}
        env:
          SECRET: ${{ secrets.GH_SECRET }}
